environment:
  QTDIR: C:/Qt/5.15/msvc2019_64
  BOOST_ROOT: C:/Libraries/boost_1_77_0

configuration: Release

image: Visual Studio 2019
platform: x64

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S
  - appveyor DownloadFile "https://github.com/ossia/sdk/releases/download/sdk18/sdk-msvc-release.zip" -FileName sdk.zip
  - 7z x sdk.zip
  - appveyor DownloadFile "http://download.qt.io/official_releases/jom/jom.zip" -FileName jom.zip
  - 7z x jom.zip
  - mkdir c:\ossia-sdk
  - move portaudio c:\ossia-sdk\portaudio
  - move ffmpeg c:\ossia-sdk\ffmpeg

build_script:
  - dir C:\Qt
  - git submodule update --init --recursive
  - set PATH=%CD%;%PATH%
  - mkdir build
  - cd build

  - dir "C:\Program Files (x86)"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%" -DSCORE_PCH=1 -DOSSIA_SDK=c:/ossia-sdk -DDEPLOYMENT_BUILD=1 ..
  - cmake --build . --config Release -- -j4
  - cmake --build . --config Release --target Package

artifacts:
  - name: Installer
    path: 'build/ossia score-*.exe'
